version: "3.8"
services:

  server:
    container_name: nest_rest_api_${NODE_ENV}
    build:
      context: .
      dockerfile: Dockerfile
      target: ${NODE_ENV}
    env_file: .env
    command: npm run start:${NODE_ENV}
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./.env.dev:/app/.env
      - ./src:/app/src
      - /app/node_modules
    restart: unless-stopped
    depends_on:
      - database
    networks:
      - server-net

  database:
    networks:
      - server-net
    container_name: database
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - ${POSTGRES_DB_PORT}:${POSTGRES_DB_PORT}
    volumes:
      - pgdata/:/var/lib/postgresql/data


volumes:
  pgdata:

networks:
  server-net: